services:
  web:
    build: ./event_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./event_backend/:/usr/src/event_backend/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: event_db

volumes:
    postgres_data: